using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ProtoGenerator
{
	public class CSharpWritter : IWriter
	{
		public bool WriteDesc( string ns, Dictionary<string, int> clsToMsgID, Dictionary<string, string> responseToMsgID, string outputPath, ref string error )
		{
			StringBuilder sb = new StringBuilder();

			sb.AppendLine( "//<auto-generated>\r\n//\tGenerated by proto generator.  DO NOT EDIT!\r\n//</auto-generated>" );
			sb.AppendLine( "//ReSharper disable CheckNamespace" );
			sb.AppendLine( "using System.Collections.Generic;" );
			sb.AppendLine();
			sb.AppendLine( $"namespace {ns} {{" );
			sb.AppendLine( "\tpublic static class ProtoDesc {" );

			sb.AppendLine( "\t\t#region mappings" );
			//type to id
			sb.AppendLine( $"\t\tprivate static readonly Dictionary<System.Type, {ns}.MsgID> _TYPE2ID = new Dictionary<System.Type, {ns}.MsgID> {{" );
			foreach ( KeyValuePair<string, int> kv in clsToMsgID )
				sb.AppendLine( $"\t\t\t{{typeof({ns}.{kv.Key.Replace( '_', '.' )}), ({ns}.MsgID){kv.Value}}}," );
			sb.AppendLine( "\t\t};" );
			sb.AppendLine();

			//id to type
			sb.AppendLine( $"\t\tprivate static readonly Dictionary<{ns}.MsgID, System.Type> _ID2TYPE = new Dictionary<{ns}.MsgID, System.Type> {{" );
			foreach ( KeyValuePair<string, int> kv in clsToMsgID )
				sb.AppendLine( $"\t\t\t{{({ns}.MsgID){kv.Value}, typeof({ns}.{kv.Key.Replace( '_', '.' )})}}," );
			sb.AppendLine( "\t\t};" );

			sb.AppendLine( "\t\t#endregion" );
			sb.AppendLine();

			sb.AppendLine( "\t\t#region create message static functions" );
			//CreateMessageByID
			sb.AppendLine( "\t\tpublic static Google.Protobuf.IMessage CreateMsgByID(int msgID) {" );
			foreach ( KeyValuePair<string, int> kv in clsToMsgID )
			{
				sb.AppendLine( $"\t\t\tif (msgID == {kv.Value})" );
				sb.AppendLine( $"\t\t\t\treturn new {ns}.{kv.Key.Replace( '_', '.' )}();" );
			}
			sb.AppendLine( "\t\t\treturn null;" );
			sb.AppendLine( "\t\t}" );

			sb.AppendLine( "\t\t#endregion" );
			sb.AppendLine();
			//end CreateMessageByID

			sb.AppendLine( "\t\t#region get message static functions" );
			sb.AppendLine( "\t\tpublic static Protos.MsgID GetMsgID( System.Type type ) => _TYPE2ID[type];" );
			sb.AppendLine();

			sb.AppendLine( "\t\tpublic static Protos.MsgID GetMsgID<T>() where T : Google.Protobuf.IMessage => _TYPE2ID[typeof( T )];" );
			sb.AppendLine();

			sb.AppendLine( "\t\tpublic static Protos.MsgID GetMsgID( this Google.Protobuf.IMessage message ) => _TYPE2ID[message.GetType()];" );
			sb.AppendLine();

			sb.AppendLine( "\t\tpublic static Protos.MsgID GetMsgID<T>( this Google.Protobuf.IMessage<T> message ) where T : Google.Protobuf.IMessage<T> => _TYPE2ID[message.GetType()];" );
			sb.AppendLine( "\t\t#endregion" );
			sb.AppendLine();

			//CreateRespMessageByID
			sb.AppendLine( "\t\t#region response message static functions" );
			foreach ( KeyValuePair<string, string> kv in responseToMsgID )
			{
				string dest = kv.Value.Replace( '_', '.' );
				sb.AppendLine( $"\t\tpublic static {ns}.{dest} R_{kv.Key}() => new {ns}.{dest}();" );
				sb.AppendLine();
			}
			sb.AppendLine( "\t\t#endregion" );
			//end CreateRespMessageByID

			sb.AppendLine( "\t} //end class" );
			sb.AppendLine( "} //end namespace" );
			try
			{
				File.WriteAllText( Path.Combine( outputPath, "ProtoDesc.cs" ), sb.ToString(), Encoding.UTF8 );
			}
			catch ( Exception e )
			{
				error = e.ToString();
				return false;
			}
			return true;
		}
	}
}