// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GC2LS.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos.GC2LS {

  /// <summary>Holder for reflection information generated from GC2LS.proto</summary>
  public static partial class GC2LSReflection {

    #region Descriptor
    /// <summary>File descriptor for GC2LS.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GC2LSReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtHQzJMUy5wcm90bxIMUHJvdG9zLkdDMkxTGgxHbG9iYWwucHJvdG8idgoL",
            "QXNrUmVnaXN0ZXISHgoGcGFja2V0GAEgASgLMg4uUHJvdG9zLlBhY2tldBIL",
            "CgNzZGsYAiABKAUSDAoEbmFtZRgDIAEoCRIOCgZwYXNzd2QYBCABKAkSEAoI",
            "cGxhdGZvcm0YBSABKA0SCgoCaXAYBiABKAkiXAoIQXNrTG9naW4SHgoGcGFj",
            "a2V0GAEgASgLMg4uUHJvdG9zLlBhY2tldBIQCghwbGF0Zm9ybRgCIAEoDRIL",
            "CgN1aW4YAyABKAkSEQoJc2Vzc2lvbmlkGAQgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protos.GlobalReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.GC2LS.AskRegister), global::Protos.GC2LS.AskRegister.Parser, new[]{ "Packet", "Sdk", "Name", "Passwd", "Platform", "Ip" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.GC2LS.AskLogin), global::Protos.GC2LS.AskLogin.Parser, new[]{ "Packet", "Platform", "Uin", "Sessionid" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AskRegister : pb::IMessage<AskRegister> {
    private static readonly pb::MessageParser<AskRegister> _parser = new pb::MessageParser<AskRegister>(() => new AskRegister());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AskRegister> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.GC2LS.GC2LSReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AskRegister() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AskRegister(AskRegister other) : this() {
      packet_ = other.packet_ != null ? other.packet_.Clone() : null;
      sdk_ = other.sdk_;
      name_ = other.name_;
      passwd_ = other.passwd_;
      platform_ = other.platform_;
      ip_ = other.ip_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AskRegister Clone() {
      return new AskRegister(this);
    }

    /// <summary>Field number for the "packet" field.</summary>
    public const int PacketFieldNumber = 1;
    private global::Protos.Packet packet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protos.Packet Packet {
      get { return packet_; }
      set {
        packet_ = value;
      }
    }

    /// <summary>Field number for the "sdk" field.</summary>
    public const int SdkFieldNumber = 2;
    private int sdk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Sdk {
      get { return sdk_; }
      set {
        sdk_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "passwd" field.</summary>
    public const int PasswdFieldNumber = 4;
    private string passwd_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Passwd {
      get { return passwd_; }
      set {
        passwd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "platform" field.</summary>
    public const int PlatformFieldNumber = 5;
    private uint platform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Platform {
      get { return platform_; }
      set {
        platform_ = value;
      }
    }

    /// <summary>Field number for the "ip" field.</summary>
    public const int IpFieldNumber = 6;
    private string ip_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ip {
      get { return ip_; }
      set {
        ip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AskRegister);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AskRegister other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Packet, other.Packet)) return false;
      if (Sdk != other.Sdk) return false;
      if (Name != other.Name) return false;
      if (Passwd != other.Passwd) return false;
      if (Platform != other.Platform) return false;
      if (Ip != other.Ip) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (packet_ != null) hash ^= Packet.GetHashCode();
      if (Sdk != 0) hash ^= Sdk.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Passwd.Length != 0) hash ^= Passwd.GetHashCode();
      if (Platform != 0) hash ^= Platform.GetHashCode();
      if (Ip.Length != 0) hash ^= Ip.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (packet_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Packet);
      }
      if (Sdk != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Sdk);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Passwd.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Passwd);
      }
      if (Platform != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Platform);
      }
      if (Ip.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Ip);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (packet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Packet);
      }
      if (Sdk != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sdk);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Passwd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Passwd);
      }
      if (Platform != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Platform);
      }
      if (Ip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ip);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AskRegister other) {
      if (other == null) {
        return;
      }
      if (other.packet_ != null) {
        if (packet_ == null) {
          packet_ = new global::Protos.Packet();
        }
        Packet.MergeFrom(other.Packet);
      }
      if (other.Sdk != 0) {
        Sdk = other.Sdk;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Passwd.Length != 0) {
        Passwd = other.Passwd;
      }
      if (other.Platform != 0) {
        Platform = other.Platform;
      }
      if (other.Ip.Length != 0) {
        Ip = other.Ip;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (packet_ == null) {
              packet_ = new global::Protos.Packet();
            }
            input.ReadMessage(packet_);
            break;
          }
          case 16: {
            Sdk = input.ReadInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Passwd = input.ReadString();
            break;
          }
          case 40: {
            Platform = input.ReadUInt32();
            break;
          }
          case 50: {
            Ip = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AskLogin : pb::IMessage<AskLogin> {
    private static readonly pb::MessageParser<AskLogin> _parser = new pb::MessageParser<AskLogin>(() => new AskLogin());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AskLogin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.GC2LS.GC2LSReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AskLogin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AskLogin(AskLogin other) : this() {
      packet_ = other.packet_ != null ? other.packet_.Clone() : null;
      platform_ = other.platform_;
      uin_ = other.uin_;
      sessionid_ = other.sessionid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AskLogin Clone() {
      return new AskLogin(this);
    }

    /// <summary>Field number for the "packet" field.</summary>
    public const int PacketFieldNumber = 1;
    private global::Protos.Packet packet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protos.Packet Packet {
      get { return packet_; }
      set {
        packet_ = value;
      }
    }

    /// <summary>Field number for the "platform" field.</summary>
    public const int PlatformFieldNumber = 2;
    private uint platform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Platform {
      get { return platform_; }
      set {
        platform_ = value;
      }
    }

    /// <summary>Field number for the "uin" field.</summary>
    public const int UinFieldNumber = 3;
    private string uin_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uin {
      get { return uin_; }
      set {
        uin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sessionid" field.</summary>
    public const int SessionidFieldNumber = 4;
    private string sessionid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sessionid {
      get { return sessionid_; }
      set {
        sessionid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AskLogin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AskLogin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Packet, other.Packet)) return false;
      if (Platform != other.Platform) return false;
      if (Uin != other.Uin) return false;
      if (Sessionid != other.Sessionid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (packet_ != null) hash ^= Packet.GetHashCode();
      if (Platform != 0) hash ^= Platform.GetHashCode();
      if (Uin.Length != 0) hash ^= Uin.GetHashCode();
      if (Sessionid.Length != 0) hash ^= Sessionid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (packet_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Packet);
      }
      if (Platform != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Platform);
      }
      if (Uin.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uin);
      }
      if (Sessionid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Sessionid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (packet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Packet);
      }
      if (Platform != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Platform);
      }
      if (Uin.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uin);
      }
      if (Sessionid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sessionid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AskLogin other) {
      if (other == null) {
        return;
      }
      if (other.packet_ != null) {
        if (packet_ == null) {
          packet_ = new global::Protos.Packet();
        }
        Packet.MergeFrom(other.Packet);
      }
      if (other.Platform != 0) {
        Platform = other.Platform;
      }
      if (other.Uin.Length != 0) {
        Uin = other.Uin;
      }
      if (other.Sessionid.Length != 0) {
        Sessionid = other.Sessionid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (packet_ == null) {
              packet_ = new global::Protos.Packet();
            }
            input.ReadMessage(packet_);
            break;
          }
          case 16: {
            Platform = input.ReadUInt32();
            break;
          }
          case 26: {
            Uin = input.ReadString();
            break;
          }
          case 34: {
            Sessionid = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
