// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LSToGC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos.LSToGC {

  /// <summary>Holder for reflection information generated from LSToGC.proto</summary>
  public static partial class LSToGCReflection {

    #region Descriptor
    /// <summary>File descriptor for LSToGC.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LSToGCReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxMU1RvR0MucHJvdG8SDVByb3Rvcy5MU1RvR0MaDEdsb2JhbC5wcm90byJP",
            "CgZSZXN1bHQSHgoGcGFja2V0GAEgASgLMg4uUHJvdG9zLlBhY2tldBIlCgZy",
            "ZXN1bHQYAiABKAsyFS5Qcm90b3MuTFNUb0dDLlJlc3VsdCLdAQoGQlNBZGRy",
            "Eh4KBnBhY2tldBgBIAEoCzIOLlByb3Rvcy5QYWNrZXQSNAoKc2VydmVyaW5m",
            "bxgCIAMoCzIgLlByb3Rvcy5MU1RvR0MuQlNBZGRyLlNlcnZlckluZm8afQoK",
            "U2VydmVySW5mbxIeCgZwYWNrZXQYASABKAsyDi5Qcm90b3MuUGFja2V0EhIK",
            "CnNlcnZlck5hbWUYAiABKAkSEgoKc2VydmVyQWRkchgDIAEoCRISCgpzZXJ2",
            "ZXJQb3J0GAQgASgFEhMKC3NlcnZlclN0YXRlGAUgASgFKloKB0VSZXN1bHQS",
            "CwoHU3VjY2VzcxAAEgoKBkZhaWxlZBABEhIKDlVzZXJuYW1lRXhpc3RzEAIS",
            "DwoLSWxsZWdhbE5hbWUQAxIRCg1JbGxlZ2FsUGFzc3dkEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protos.GlobalReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protos.LSToGC.EResult), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.LSToGC.Result), global::Protos.LSToGC.Result.Parser, new[]{ "Packet", "Result_" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.LSToGC.BSAddr), global::Protos.LSToGC.BSAddr.Parser, new[]{ "Packet", "Serverinfo" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Protos.LSToGC.BSAddr.Types.ServerInfo), global::Protos.LSToGC.BSAddr.Types.ServerInfo.Parser, new[]{ "Packet", "ServerName", "ServerAddr", "ServerPort", "ServerState" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  public enum EResult {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("Failed")] Failed = 1,
    [pbr::OriginalName("UsernameExists")] UsernameExists = 2,
    [pbr::OriginalName("IllegalName")] IllegalName = 3,
    [pbr::OriginalName("IllegalPasswd")] IllegalPasswd = 4,
  }

  #endregion

  #region Messages
  public sealed partial class Result : pb::IMessage<Result> {
    private static readonly pb::MessageParser<Result> _parser = new pb::MessageParser<Result>(() => new Result());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Result> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.LSToGC.LSToGCReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Result() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Result(Result other) : this() {
      packet_ = other.packet_ != null ? other.packet_.Clone() : null;
      result_ = other.result_ != null ? other.result_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Result Clone() {
      return new Result(this);
    }

    /// <summary>Field number for the "packet" field.</summary>
    public const int PacketFieldNumber = 1;
    private global::Protos.Packet packet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protos.Packet Packet {
      get { return packet_; }
      set {
        packet_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int Result_FieldNumber = 2;
    private global::Protos.LSToGC.Result result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protos.LSToGC.Result Result_ {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Result);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Result other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Packet, other.Packet)) return false;
      if (!object.Equals(Result_, other.Result_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (packet_ != null) hash ^= Packet.GetHashCode();
      if (result_ != null) hash ^= Result_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (packet_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Packet);
      }
      if (result_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Result_);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (packet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Packet);
      }
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result_);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Result other) {
      if (other == null) {
        return;
      }
      if (other.packet_ != null) {
        if (packet_ == null) {
          packet_ = new global::Protos.Packet();
        }
        Packet.MergeFrom(other.Packet);
      }
      if (other.result_ != null) {
        if (result_ == null) {
          result_ = new global::Protos.LSToGC.Result();
        }
        Result_.MergeFrom(other.Result_);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (packet_ == null) {
              packet_ = new global::Protos.Packet();
            }
            input.ReadMessage(packet_);
            break;
          }
          case 18: {
            if (result_ == null) {
              result_ = new global::Protos.LSToGC.Result();
            }
            input.ReadMessage(result_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class BSAddr : pb::IMessage<BSAddr> {
    private static readonly pb::MessageParser<BSAddr> _parser = new pb::MessageParser<BSAddr>(() => new BSAddr());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BSAddr> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.LSToGC.LSToGCReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BSAddr() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BSAddr(BSAddr other) : this() {
      packet_ = other.packet_ != null ? other.packet_.Clone() : null;
      serverinfo_ = other.serverinfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BSAddr Clone() {
      return new BSAddr(this);
    }

    /// <summary>Field number for the "packet" field.</summary>
    public const int PacketFieldNumber = 1;
    private global::Protos.Packet packet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protos.Packet Packet {
      get { return packet_; }
      set {
        packet_ = value;
      }
    }

    /// <summary>Field number for the "serverinfo" field.</summary>
    public const int ServerinfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Protos.LSToGC.BSAddr.Types.ServerInfo> _repeated_serverinfo_codec
        = pb::FieldCodec.ForMessage(18, global::Protos.LSToGC.BSAddr.Types.ServerInfo.Parser);
    private readonly pbc::RepeatedField<global::Protos.LSToGC.BSAddr.Types.ServerInfo> serverinfo_ = new pbc::RepeatedField<global::Protos.LSToGC.BSAddr.Types.ServerInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Protos.LSToGC.BSAddr.Types.ServerInfo> Serverinfo {
      get { return serverinfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BSAddr);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BSAddr other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Packet, other.Packet)) return false;
      if(!serverinfo_.Equals(other.serverinfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (packet_ != null) hash ^= Packet.GetHashCode();
      hash ^= serverinfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (packet_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Packet);
      }
      serverinfo_.WriteTo(output, _repeated_serverinfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (packet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Packet);
      }
      size += serverinfo_.CalculateSize(_repeated_serverinfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BSAddr other) {
      if (other == null) {
        return;
      }
      if (other.packet_ != null) {
        if (packet_ == null) {
          packet_ = new global::Protos.Packet();
        }
        Packet.MergeFrom(other.Packet);
      }
      serverinfo_.Add(other.serverinfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (packet_ == null) {
              packet_ = new global::Protos.Packet();
            }
            input.ReadMessage(packet_);
            break;
          }
          case 18: {
            serverinfo_.AddEntriesFrom(input, _repeated_serverinfo_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the BSAddr message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class ServerInfo : pb::IMessage<ServerInfo> {
        private static readonly pb::MessageParser<ServerInfo> _parser = new pb::MessageParser<ServerInfo>(() => new ServerInfo());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ServerInfo> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Protos.LSToGC.BSAddr.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ServerInfo() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ServerInfo(ServerInfo other) : this() {
          packet_ = other.packet_ != null ? other.packet_.Clone() : null;
          serverName_ = other.serverName_;
          serverAddr_ = other.serverAddr_;
          serverPort_ = other.serverPort_;
          serverState_ = other.serverState_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ServerInfo Clone() {
          return new ServerInfo(this);
        }

        /// <summary>Field number for the "packet" field.</summary>
        public const int PacketFieldNumber = 1;
        private global::Protos.Packet packet_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Protos.Packet Packet {
          get { return packet_; }
          set {
            packet_ = value;
          }
        }

        /// <summary>Field number for the "serverName" field.</summary>
        public const int ServerNameFieldNumber = 2;
        private string serverName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ServerName {
          get { return serverName_; }
          set {
            serverName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "serverAddr" field.</summary>
        public const int ServerAddrFieldNumber = 3;
        private string serverAddr_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ServerAddr {
          get { return serverAddr_; }
          set {
            serverAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "serverPort" field.</summary>
        public const int ServerPortFieldNumber = 4;
        private int serverPort_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int ServerPort {
          get { return serverPort_; }
          set {
            serverPort_ = value;
          }
        }

        /// <summary>Field number for the "serverState" field.</summary>
        public const int ServerStateFieldNumber = 5;
        private int serverState_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int ServerState {
          get { return serverState_; }
          set {
            serverState_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as ServerInfo);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ServerInfo other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Packet, other.Packet)) return false;
          if (ServerName != other.ServerName) return false;
          if (ServerAddr != other.ServerAddr) return false;
          if (ServerPort != other.ServerPort) return false;
          if (ServerState != other.ServerState) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (packet_ != null) hash ^= Packet.GetHashCode();
          if (ServerName.Length != 0) hash ^= ServerName.GetHashCode();
          if (ServerAddr.Length != 0) hash ^= ServerAddr.GetHashCode();
          if (ServerPort != 0) hash ^= ServerPort.GetHashCode();
          if (ServerState != 0) hash ^= ServerState.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (packet_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Packet);
          }
          if (ServerName.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(ServerName);
          }
          if (ServerAddr.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(ServerAddr);
          }
          if (ServerPort != 0) {
            output.WriteRawTag(32);
            output.WriteInt32(ServerPort);
          }
          if (ServerState != 0) {
            output.WriteRawTag(40);
            output.WriteInt32(ServerState);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (packet_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Packet);
          }
          if (ServerName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerName);
          }
          if (ServerAddr.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerAddr);
          }
          if (ServerPort != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerPort);
          }
          if (ServerState != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerState);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ServerInfo other) {
          if (other == null) {
            return;
          }
          if (other.packet_ != null) {
            if (packet_ == null) {
              packet_ = new global::Protos.Packet();
            }
            Packet.MergeFrom(other.Packet);
          }
          if (other.ServerName.Length != 0) {
            ServerName = other.ServerName;
          }
          if (other.ServerAddr.Length != 0) {
            ServerAddr = other.ServerAddr;
          }
          if (other.ServerPort != 0) {
            ServerPort = other.ServerPort;
          }
          if (other.ServerState != 0) {
            ServerState = other.ServerState;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (packet_ == null) {
                  packet_ = new global::Protos.Packet();
                }
                input.ReadMessage(packet_);
                break;
              }
              case 18: {
                ServerName = input.ReadString();
                break;
              }
              case 26: {
                ServerAddr = input.ReadString();
                break;
              }
              case 32: {
                ServerPort = input.ReadInt32();
                break;
              }
              case 40: {
                ServerState = input.ReadInt32();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
