//<auto-generated>
//	Generated by proto generator.  DO NOT EDIT!
//</auto-generated>
//ReSharper disable CheckNamespace
using System.Collections.Generic;

namespace Protos {
	public static class ProtoDesc {
		private static readonly Dictionary<System.Type, Protos.MsgID> _TYPE2ID = new Dictionary<System.Type, Protos.MsgID> {
			{typeof(Protos.GCToLS.AskRegister), (Protos.MsgID)100},
			{typeof(Protos.GCToLS.AskLogin), (Protos.MsgID)101},
			{typeof(Protos.LSToGC.Result), (Protos.MsgID)200},
			{typeof(Protos.LSToGC.BSAddr), (Protos.MsgID)201},
		};

		private static readonly Dictionary<Protos.MsgID, System.Type> _ID2TYPE = new Dictionary<Protos.MsgID, System.Type> {
			{(Protos.MsgID)100, typeof(Protos.GCToLS.AskRegister)},
			{(Protos.MsgID)101, typeof(Protos.GCToLS.AskLogin)},
			{(Protos.MsgID)200, typeof(Protos.LSToGC.Result)},
			{(Protos.MsgID)201, typeof(Protos.LSToGC.BSAddr)},
		};

		private static readonly Dictionary<System.Type, int> _TYPE2REPSID = new Dictionary<System.Type, int> {
			{typeof(Protos.GCToLS.AskRegister), 200},
			{typeof(Protos.GCToLS.AskLogin), 200},
		};

		public static Google.Protobuf.IMessage CreateMessageByID(Protos.MsgID msgID) => CreateMessageByID((int)msgID);

		public static Google.Protobuf.IMessage CreateMessageByID(int msgID) {
			if (msgID == 100)
				return new Protos.GCToLS.AskRegister();
			if (msgID == 101)
				return new Protos.GCToLS.AskLogin();
			if (msgID == 200)
				return new Protos.LSToGC.Result();
			if (msgID == 201)
				return new Protos.LSToGC.BSAddr();
			return null;
		}

		public static Google.Protobuf.IMessage CreateRespMessageByID(int msgID) => CreateMessageByID((Protos.MsgID)msgID);

		public static Google.Protobuf.IMessage CreateRespMessageByID(Protos.MsgID msgID) {
			if (! _TYPE2REPSID.TryGetValue(_ID2TYPE[msgID], out int respID ))
				return null;
			if (respID == 200)
				return new Protos.LSToGC.Result();
			if (respID == 200)
				return new Protos.LSToGC.Result();
			return null;
		}
	} //end class
} //end namespace
