//<auto-generated>
//	Generated by proto generator.  DO NOT EDIT!
//</auto-generated>
//ReSharper disable CheckNamespace
import { Protos } from "../libs/protos";

export class ProtoDesc {
	private static readonly _TYPE2ID = new Map<new () => any, Protos.MsgID>([
		[Protos.GC2LS.AskRegister, <Protos.MsgID>100],
		[Protos.GC2LS.AskLogin, <Protos.MsgID>101],
		[Protos.LS2GC.Result, <Protos.MsgID>200],
		[Protos.LS2GC.GSInfo, <Protos.MsgID>201],
		[Protos.GS2CS.ReportState, <Protos.MsgID>300],
		[Protos.CS2LS.GSInfos, <Protos.MsgID>400],
		[Protos.CS2LS.GSInfo, <Protos.MsgID>401],
		[Protos.CS2LS.GSLost, <Protos.MsgID>402],
	]);

	private static readonly _ID2TYPE = new Map<Protos.MsgID, new () => any>([
		[<Protos.MsgID>100, Protos.GC2LS.AskRegister],
		[<Protos.MsgID>101, Protos.GC2LS.AskLogin],
		[<Protos.MsgID>200, Protos.LS2GC.Result],
		[<Protos.MsgID>201, Protos.LS2GC.GSInfo],
		[<Protos.MsgID>300, Protos.GS2CS.ReportState],
		[<Protos.MsgID>400, Protos.CS2LS.GSInfos],
		[<Protos.MsgID>401, Protos.CS2LS.GSInfo],
		[<Protos.MsgID>402, Protos.CS2LS.GSLost],
	]);

	public static CreateMsgByID(msgID: Protos.MsgID): any {
		let c = ProtoDesc._ID2TYPE.get(msgID);
		return c == null ? null : new c();
	}

	public static GetMsgIDByType(type: new () => any): Protos.MsgID { return ProtoDesc._TYPE2ID.get(type); }

	public static GetMsgID(message: any): Protos.MsgID { return ProtoDesc._TYPE2ID.get(message.constructor); }

	public static R_GC2LS_AskRegister(): Protos.LS2GC.Result { return new Protos.LS2GC.Result(); }

	public static R_GC2LS_AskLogin(): Protos.LS2GC.Result { return new Protos.LS2GC.Result(); }

} //end class
